Add prettify to validate_indices
pinin4fjords/shinyngs pull request #59
Opened 2024-01-05 10:32 UTC by WackerO

ATM, a call to `prettifyVariablename` is missing in `validate_indices` while `stringsToNamedVector` contains a prettify. This leads to `exploratory_plots.R` throwing an `error Invalid` assays because it will e.g. compare the strings `raw` and `Raw`. This PR adds the prettify to fix this issue.

2024-01-05 15:21 UTC, pinin4fjords commented on R/accessory.R
> +    indices <- lapply(indices, prettifyVariablename)
You'll need an unlist here to maintain the same type as simpleSplit.

2024-01-10 13:08 UTC, pinin4fjords requested changes
Sorry, just looking at this properly. 

You'll notice that stringsToNamedVector has the prettification as a parameter. It should probably be the same in this function (with the same default), so that things can be matched.

2024-01-11 07:30 UTC, WackerO commented
> Sorry, just looking at this properly.
> 
> You'll notice that stringsToNamedVector has the prettification as a parameter. It should probably be the same in this function (with the same default), so that things can be matched.

Ah yes sure, done!

2024-01-11 09:57 UTC, pinin4fjords approved these changes
LGTM

2024-01-11 09:58 UTC, merged